name: Build and deploy .NET Core application to Azure Web App

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: BachelorParis202420250918111623 
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 8.0.x
  WORKING_DIRECTORY: ./BachelorParis2024
  AZURE_WEBAPP_PACKAGE_PATH: ./publish

jobs:
  build-and-deploy:
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with: 
        dotnet-version: '8.0.401'
    - name: Restore
      run: dotnet restore "${{ env.WORKING_DIRECTORY }}"
    - name: Build
      run: dotnet build "${{ env.WORKING_DIRECTORY }}" --configuration ${{ env.CONFIGURATION }} --no-restore
    - name: Test
      run: dotnet test "${{ env.WORKING_DIRECTORY }}" --no-build
    - name: Publish
      run: dotnet publish ./BachelorParis2024 -c Release -o ./publish
    - name: Publish Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
  deploy:
    runs-on: windows-latest
    needs: build-and-deploy
    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v4
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Restore .NET tools
      run: dotnet tool restore
      working-directory: .
    - name: Run EF Core migrations
      run: dotnet tool run ef database update --project ./BachelorParis2024.Repository --startup-project ./BachelorParis2024
      env:
            ConnectionStrings__AZURE_SQL_CONNECTIONSTRING: ${{ secrets.AZURE_SQL_CONNECTIONSTRING}}
    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.BachelorParis202420250918111623 }}
        slot-name: "production"
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
